[package]
name = "order-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-threadpool = "0.3.3"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "chrono", "uuid", "serde_json"] }
diesel_migrations = "2.0.0"
async-trait = "0.1.58"
dotenv = { version = "0.15" }
testcontainers = { version = "0.14.0" }
env_logger = "0.10.0"
log = "0.4"
serde_json = "1.0"
futures-util = "0.3.26"
uuid = { version = "1.10.0", features = ["v4", "serde"] }
rust_decimal = { version = "1.30.0", features = ["serde", "db-diesel-postgres"] }
chrono = { version = "0.4", features = ["serde"] }
strum = "0.26"
strum_macros = "0.26"
